[package]
name = "vaultsync-wasm"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
vaultsync-core = { path = "../vaultsync-core", default-features = false, features = ["async-runtime"] }
vaultsync-transport-webrtc = { path = "../vaultsync-transport-webrtc" }
wasm-bindgen = "0.2"
web-sys = { version = "0.3", features = [
    "WebSocket", "BroadcastChannel", "Window", "Navigator",
    "Storage", "Crypto", "SubtleCrypto",
    "StorageManager", "FileSystemDirectoryHandle",
    "FileSystemFileHandle", "FileSystemWritableFileStream",
    "FileSystemGetFileOptions", "FileSystemGetDirectoryOptions",
    "FileSystemCreateWritableOptions", "FileSystemRemoveOptions",
    "Blob", "File", "WritableStream", "Lock", "LockManager",
    "IdbDatabase", "IdbTransaction", "IdbObjectStore",
    "IdbFactory", "IdbRequest", "IdbOpenDbRequest",
    "IdbTransactionMode", "IdbVersionChangeEvent",
    "Event", "EventTarget", "BinaryType", "MessageEvent",
    "Performance", "Request", "RequestInit", "Response", "console"
] }
js-sys = "0.3"
console_error_panic_hook = "0.1"
getrandom = { version = "0.2", features = ["js"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
wasm-bindgen-futures = "0.4"
async-trait = "0.1"
tracing = "0.1"
futures = "0.3"
uuid = { version = "1", features = ["v4", "js"] }

[dev-dependencies]
wasm-bindgen-test = "0.3"

