[workspace]
resolver = "2"
members = [
    "crates/drift-core",
    "crates/drift-wasm",
    "crates/drift-coordinator-postgres",
    "crates/drift-coordinator-redis",
    "crates/drift-coordinator-sqlite",
    "crates/drift-coordinator-memory",
    "crates/drift-coordinator-http",
    "crates/drift-coordinator-server",
    "crates/drift-cli",
    "crates/drift-fuzz",
    "crates/drift-napi",
    "crates/drift-transport-webrtc",
    "crates/drift-coordinator-cf",
    "crates/drift-conformance",
    "crates/drift-transport-libp2p",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["Drift Contributors"]
